// Patched utils - reads credentials from environment variables
// Auto-generated by Poke MCP deployment workflow
// This makes the MCP server completely stateless

import { SpotifyApi } from '@spotify/web-api-ts-sdk';

export function loadSpotifyConfig() {
  const config = {
    clientId: process.env.SPOTIFY_CLIENT_ID || process.env.MCP_CLIENT_ID || '',
    clientSecret: process.env.SPOTIFY_CLIENT_SECRET || process.env.MCP_CLIENT_SECRET || '',
    redirectUri: process.env.SPOTIFY_REDIRECT_URI || 'http://localhost:8888/callback',
    accessToken: process.env.SPOTIFY_ACCESS_TOKEN || process.env.MCP_ACCESS_TOKEN || undefined,
    refreshToken: process.env.SPOTIFY_REFRESH_TOKEN || process.env.MCP_REFRESH_TOKEN || undefined,
  };

  if (!config.clientId || !config.clientSecret) {
    throw new Error('SPOTIFY_CLIENT_ID and SPOTIFY_CLIENT_SECRET environment variables are required');
  }

  return config;
}

export function saveSpotifyConfig(config) {
  // No-op in stateless mode - credentials are managed externally
  console.log('saveSpotifyConfig called but ignored in stateless mode');
}

let cachedSpotifyApi = null;

export function createSpotifyApi() {
  if (cachedSpotifyApi) {
    return cachedSpotifyApi;
  }

  const config = loadSpotifyConfig();

  if (config.accessToken && config.refreshToken) {
    const accessToken = {
      access_token: config.accessToken,
      token_type: 'Bearer',
      expires_in: 3600 * 24 * 30,
      refresh_token: config.refreshToken,
    };

    cachedSpotifyApi = SpotifyApi.withAccessToken(config.clientId, accessToken);
    return cachedSpotifyApi;
  }

  cachedSpotifyApi = SpotifyApi.withClientCredentials(config.clientId, config.clientSecret);
  return cachedSpotifyApi;
}

// Stub for authorizeSpotify - not used in stateless mode
export function authorizeSpotify() {
  throw new Error('OAuth authorization is not supported in stateless mode. Tokens must be provided via environment variables.');
}
