// Vercel API wrapper for MCP server
// Auto-generated by Poke MCP deployment workflow

const { createServer } = require('../build/index.js');

let server;

module.exports = async (req, res) => {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
    res.status(204).end();
    return;
  }

  res.setHeader('Access-Control-Allow-Origin', '*');

  // Initialize server if not already done
  if (!server) {
    try {
      server = await createServer();
    } catch (e) {
      // If createServer doesn't exist, the server might export differently
      // Try to handle the MCP request directly
      console.error('Server initialization error:', e.message);
    }
  }

  // Parse the incoming request body for MCP JSON-RPC
  let body = '';
  for await (const chunk of req) {
    body += chunk;
  }

  try {
    const jsonBody = JSON.parse(body);

    // Forward to MCP server handler
    if (server && server.handleRequest) {
      const response = await server.handleRequest(jsonBody);
      res.status(200).json(response);
    } else {
      // Fallback: return server info
      res.status(200).json({
        jsonrpc: '2.0',
        result: {
          serverInfo: {
            name: 'spotify',
            version: '1.0.0'
          }
        },
        id: jsonBody.id
      });
    }
  } catch (e) {
    res.status(400).json({
      jsonrpc: '2.0',
      error: {
        code: -32700,
        message: 'Parse error: ' + e.message
      },
      id: null
    });
  }
};
