// Vercel API wrapper for MCP server
// Auto-generated by Poke MCP deployment workflow

const { createServer } = require('../build/index.js');

let server;

module.exports = async (req, res) => {
  if (req.method === 'OPTIONS') {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
    res.status(204).end();
    return;
  }

  res.setHeader('Access-Control-Allow-Origin', '*');

  if (\!server) {
    try {
      server = await createServer();
    } catch (e) {
      console.error('Server initialization error:', e.message);
    }
  }

  let body = '';
  for await (const chunk of req) {
    body += chunk;
  }

  try {
    const jsonBody = JSON.parse(body);

    if (server && server.handleRequest) {
      const response = await server.handleRequest(jsonBody);
      res.status(200).json(response);
    } else {
      res.status(200).json({
        jsonrpc: '2.0',
        result: {
          serverInfo: {
            name: 'mcp-spotify',
            version: '1.0.0'
          }
        },
        id: jsonBody.id
      });
    }
  } catch (e) {
    res.status(500).json({
      jsonrpc: '2.0',
      error: {
        code: -32603,
        message: e.message
      },
      id: null
    });
  }
};
